# Generated by Django 4.1.4 on 2023-01-19 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aktor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imię", models.CharField(max_length=45)),
                ("nazwisko", models.CharField(max_length=45)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=80)),
                ("opis", models.CharField(max_length=250)),
                ("rok_produkcji", models.IntegerField()),
                ("ilosc_ocen", models.IntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField()),
                (
                    "aktorzy",
                    models.ManyToManyField(related_name="aktorzy", to="Film_.aktor"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=30)),
                ("opis", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Rezyser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imię", models.CharField(max_length=45)),
                ("nazwisko", models.CharField(max_length=45)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wartość", models.IntegerField()),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "film",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oceny",
                        to="Film_.film",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="kategoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Film_.kategoria"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="rezyser",
            field=models.ManyToManyField(related_name="rezyser", to="Film_.rezyser"),
        ),
    ]
