# Generated by Django 4.1.4 on 2023-01-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Film_", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="film", name="ilosc_ocen",),
    ]
