# Generated by Django 4.1.2 on 2023-01-23 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Film_', '0002_remove_film_ilosc_ocen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='Film_.film'),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='wartość',
            field=models.IntegerField(choices=[('1', 'Okropny'), ('2', 'Słaby'), ('3', 'Średni'), ('4', 'Dobry'), ('5', 'Znakomity')], default=5),
        ),
    ]
