# Generated by Django 4.1.4 on 2023-01-27 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Film_", "0003_alter_film_updated_alter_ocena_film_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocena",
            name="published_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ocena",
            name="wartość",
            field=models.IntegerField(
                choices=[
                    (1, "Okropny"),
                    (2, "Słaby"),
                    (3, "Średni"),
                    (4, "Dobry"),
                    (5, "Znakomity"),
                ]
            ),
        ),
    ]
